spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/ai_agent
    username: ai_agent
    password: 123
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
